import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH ?? 'playwright');
const base = process.env.PREVIEW_URL ?? 'http://127.0.0.1:8765/config-generator/';
const channel = process.env.BROWSER_CHANNEL ?? (process.env.CI ? 'chromium' : 'msedge');
const browser = await chromium.launch({ channel, headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
const page = await context.newPage();
const errors = [];
const requests = [];
const localFailures = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => requests.push(request.url()));
page.on('response', response => {
  if (response.url().startsWith(new URL(base).origin) && response.status() >= 400) localFailures.push(response.status());
});
await page.route('**/*', route => route.request().url().startsWith(new URL(base).origin) ? route.continue() : route.abort());
const id = key => page.locator(`[id="cg-${key}"]`);
const preview = page.locator('#cg-preview-code');
const click = name => page.getByRole('button', { name, exact: true }).click();
const section = label => page.locator('summary', { hasText: label });
async function output() {
  await id('format').selectOption('json');
  return JSON.parse(await preview.textContent());
}

try {
  await page.goto(`${base}?schema=tuic-client&mode=detail&retained=yes#query-state`);
  await page.waitForSelector('#config-generator[data-ready="true"]');
  assert.equal(await id('schema').inputValue(), 'tuic-client');
  assert.equal(await page.locator('article[aria-label="客户端配置 YAML 配置详解"]').count(), 1);
  assert.ok((await page.locator('.cg-desc-line').allTextContents()).some(line => line.includes('skip_cert_verify: false')));
  assert.ok(await page.locator('.cg-desc-line code .token.atrule').count() > 0, 'YAML keys are highlighted');
  await page.locator('#cg-desc-forward').selectOption('udp');
  assert.ok((await page.locator('.cg-desc-line').allTextContents()).some(line => line.includes('udp_forward:')));
  await id('desc-format').selectOption('toml');
  assert.equal(await page.locator('article[aria-label="客户端配置 TOML 配置详解"]').count(), 1);
  assert.equal(await page.locator('.cg-desc-document header strong').textContent(), 'client.toml');
  assert.ok((await page.locator('.cg-desc-line').allTextContents()).some(line => line.includes('[[local.udp_forward]]')));
  assert.ok(await page.locator('.cg-desc-line code .token.class-name').count() > 0, 'TOML tables are highlighted');
  await id('desc-format').selectOption('yaml');

  await id('schema').selectOption('tuic-server');
  assert.equal(new URL(page.url()).searchParams.get('schema'), 'tuic-server');
  assert.equal(new URL(page.url()).searchParams.get('retained'), 'yes');
  assert.equal(new URL(page.url()).hash, '#query-state');
  assert.ok((await page.locator('.cg-desc-line').allTextContents()).some(line => line.includes('certificate:')));
  await page.locator('#cg-desc-tls').selectOption('acme');
  const acmeLine = page.locator('.cg-desc-line').filter({ hasText: 'auto_ssl: true' });
  assert.equal((await acmeLine.getAttribute('aria-label')).includes('ACME'), true);
  await acmeLine.hover();
  assert.equal(await acmeLine.locator('[role="tooltip"]').isVisible(), true);
  mkdirSync('.cache', { recursive: true });
  await page.screenshot({ path: resolve('.cache/config-description-desktop.png'), fullPage: true });

  await click('配置生成');
  assert.equal(new URL(page.url()).searchParams.get('mode'), 'generate');
  assert.equal(await page.getByRole('heading', { name: '服务端配置文件生成器' }).count(), 1);
  assert.equal(await id('mode').count(), 0, 'Application schemas must not expose the old paired generation mode');
  await id('hostname').fill('tuic.example.com');
  assert.equal(await page.getByRole('button', { name: '下载配置', exact: true }).isEnabled(), true);
  let server = await output();
  assert.equal(server.server, '[::]:8443');
  assert.equal(Object.keys(server.users).length, 1);
  await click('＋ 添加用户');
  server = await output();
  assert.equal(Object.keys(server.users).length, 2);

  await id('tlsMode').selectOption('self');
  server = await output();
  assert.equal(server.tls.self_sign, true);
  await id('tlsMode').selectOption('acme');
  await id('email').fill('admin@example.com');
  server = await output();
  assert.equal(server.tls.auto_ssl, true);
  assert.equal(server.tls.self_sign, undefined);
  await id('tlsMode').selectOption('certificate');
  server = await output();
  assert.equal(server.data_dir, undefined);

  await section('QUIC 后端').click();
  await id('backendMode').selectOption('quiche');
  server = await output();
  assert.equal(server.backend.mode, 'quiche');
  assert.equal(server.backend.quiche.max_concurrent_bi_streams, 100);
  await section('QUIC 后端').click();
  await section('路由与出站').click();
  await id('dnsEnabled').check();
  await id('dnsMode').selectOption('custom');
  await id('dnsServers.0.server').fill('tls://1.1.1.1#cloudflare-dns.com');
  server = await output();
  assert.equal(server.dns.servers[0], 'tls://1.1.1.1#cloudflare-dns.com');
  assert.equal(server.outbound.default.type, 'direct');
  console.log('PASS: independent TUIC server schema, details, TLS, backend and routing');

  await id('schema').selectOption('tuic-client');
  assert.equal(await page.getByRole('heading', { name: '客户端配置文件生成器' }).count(), 1);
  assert.equal(await id('hostname').count(), 0);
  assert.equal(await id('host').inputValue(), '', 'Switching schemas must create an independent session');
  await id('host').fill('tuic.example.com');
  const hostControl = await id('host').elementHandle();
  await id('host').pressSequentially('.test');
  assert.equal(await hostControl.evaluate(node => node.isConnected && document.activeElement === node), true);
  await id('host').fill('tuic.example.com');
  let client = await output();
  assert.equal(client.server, 'tuic.example.com:8443');
  assert.equal(client.tls.skip_cert_verify, false);
  await id('reveal').uncheck();
  assert.equal(JSON.parse(await preview.textContent()).password, '••••••••');
  await click('复制配置');
  const copied = JSON.parse(await page.evaluate(() => navigator.clipboard.readText()));
  assert.equal(copied.password.length > 0, true);
  const pendingDownload = page.waitForEvent('download');
  await click('下载配置');
  const download = await pendingDownload;
  assert.equal(download.suggestedFilename(), 'client.json');
  assert.equal(JSON.parse(readFileSync(await download.path(), 'utf8')).password, copied.password);

  await click('＋ 添加用户');
  await id('activeUser').selectOption('1');
  client = await output();
  assert.equal(client.uuid, await id('users.1.uuid').inputValue());
  await page.getByRole('button', { name: '移除用户 1', exact: true }).click();
  assert.equal((await output()).uuid, client.uuid);

  await id('port').fill('443');
  await id('host').fill('[2001:db8::1]');
  await id('sni').fill('tuic.example.com');
  client = await output();
  assert.equal(client.server, '[2001:db8::1]:443');
  assert.equal(client.ip, '2001:db8::1');
  await section('高级选项').click();
  await id('localAuth').check();
  await id('localUsername').fill('tester');
  await id('localPassword').fill('a " \\ # 中文');
  await click('＋ 添加转发');
  await id('forwards.0.listen').fill('127.0.0.1:8080');
  await id('forwards.0.remote').fill('example.com:80');
  await id('forwards.0.protocol').selectOption('udp');
  await id('forwards.0.timeout').fill('30');
  client = await output();
  assert.equal(client.local.udp_forward[0].timeout, '30s');
  await id('reconnect').uncheck();
  assert.equal((await output()).reconnect_initial_backoff, undefined);
  console.log('PASS: independent TUIC client schema, selection, export and forwarding');

  const injection = '<img src=x onerror=alert(1)> " \\ 中文';
  await id('localUsername').fill(injection);
  await id('format').selectOption('yaml');
  assert.ok((await preview.textContent()).includes(injection.slice(0, 27)));
  await id('format').selectOption('toml');
  assert.equal(await page.locator('#config-generator img').count(), 0);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: resolve('.cache/config-generator-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.screenshot({ path: resolve('.cache/config-generator-mobile.png'), fullPage: true });
  await click('切换主题');
  assert.equal(await page.locator('.cg-shell').getAttribute('data-theme'), 'dark');
  assert.equal(await page.getByRole('link', { name: '配置说明 ↗' }).count(), 0);
  assert.equal(await page.evaluate(() => localStorage.length === 0 || !Object.keys(localStorage).some(key => /generator|password|uuid/.test(key))), true);
  assert.deepEqual(requests.filter(url => /google-analytics|googletagmanager|gtag/.test(url)), []);
  assert.deepEqual(requests.filter(url => !url.startsWith(new URL(base).origin)), []);
  assert.deepEqual(localFailures, []);
  assert.deepEqual(errors, []);
  await page.reload();
  await page.waitForSelector('#config-generator[data-ready="true"]');
  assert.equal(await id('schema').inputValue(), 'tuic-client');
  assert.equal(await id('host').inputValue(), '');
  console.log('PASS: URL state, injection safety, mobile layout, themes and no input persistence');
} finally {
  await context.close();
  await browser.close();
}
